version: '3.9'
services:
    nango-db:
        image: docker.io/postgres
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '5432:5432'
        networks:
            - nango

    nango-server:
        image: nango.docker.scarf.sh/nangohq/nango-server
        container_name: nango-server
        restart: always
        env_file:
            - .env
        ports:
            - '3003:3003'
        depends_on:
            - nango-db
        networks:
            - nango
networks:
    nango:
